# -*- coding: utf-8 -*-
"""Surrogate-Assisted Reward Design for Learning Rhythmic Standing Balance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PuxyFbsob-Pu9uz8huK5Sjn45eP7HfLO
"""

import os
import json
import math
import warnings
from dataclasses import dataclass, asdict
from pathlib import Path
from collections import deque
from typing import Dict, List, Tuple, Optional

import numpy as np
import pandas as pd
import gymnasium as gym
from gymnasium import spaces

import torch
import torch.nn as nn

from stable_baselines3 import PPO
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from scipy.signal import welch
from scipy.spatial import ConvexHull
from scipy.stats import shapiro, ttest_ind, mannwhitneyu
import joblib

warnings.filterwarnings("ignore")


# ============================================================
# Configuration
# ============================================================

SEED = 42
DATA_DIR = Path("./human_cop_data")          # Folder with human trajectories (.csv)
OUTPUT_DIR = Path("./outputs_rhythmic_standing")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SAMPLE_RATE = 20.0                           # Hz
DT = 1.0 / SAMPLE_RATE
MAX_STEPS = 16000                            # 800 s at 20 Hz
FALL_THRESHOLD_DEG = 12.0
EVAL_AGENT_TRAJ = 10
INITIAL_DESIGN_N = 6
GUIDED_ITERS = 8
CANDIDATES_PER_ITER = 64

PPO_TOTAL_TIMESTEPS = 64_000
PPO_FINAL_TIMESTEPS = 128_000
EVAL_EPISODES_FOR_SCORE = 4

np.random.seed(SEED)
torch.manual_seed(SEED)


# ============================================================
# Utilities
# ============================================================

def set_global_seed(seed: int) -> None:
    np.random.seed(seed)
    torch.manual_seed(seed)


def clip_with_eps(x: np.ndarray, low: float, high: float) -> np.ndarray:
    return np.clip(x, low, high)


def shannon_entropy_from_counts(counts: np.ndarray) -> float:
    counts = np.asarray(counts, dtype=float)
    total = counts.sum()
    if total <= 0:
        return 0.0
    p = counts[counts > 0] / total
    return float(-np.sum(p * np.log2(p)))


def safe_convex_hull_area(x: np.ndarray, y: np.ndarray) -> float:
    pts = np.column_stack([x, y])
    if len(pts) < 3:
        return 0.0
    try:
        hull = ConvexHull(pts)
        return float(hull.volume)  # 2D hull area
    except Exception:
        return 0.0


def dominant_frequency_and_centroid(signal: np.ndarray, fs: float) -> Tuple[float, float]:
    signal = np.asarray(signal, dtype=float)
    if signal.size < 8:
        return 0.0, 0.0

    nperseg = min(256, signal.size)
    f, pxx = welch(signal, fs=fs, nperseg=nperseg, scaling="density")
    if pxx.size == 0 or np.all(pxx <= 0):
        return 0.0, 0.0

    # Ignore DC for dominant frequency
    if len(f) > 1:
        idx = np.argmax(pxx[1:]) + 1
    else:
        idx = 0
    dom_f = float(f[idx])

    p = np.maximum(pxx, 0)
    if np.sum(p) <= 0:
        centroid = 0.0
    else:
        centroid = float(np.sum(f * p) / np.sum(p))
    return dom_f, centroid


def compute_entropy_2d(theta: np.ndarray, phi: np.ndarray, bins: int = 16) -> float:
    theta = np.asarray(theta, dtype=float)
    phi = np.asarray(phi, dtype=float)
    if theta.size < 4 or phi.size < 4:
        return 0.0

    # Fixed range keeps the metric comparable across trajectories
    hist, _, _ = np.histogram2d(theta, phi, bins=bins, range=[(-0.5, 0.5), (-0.5, 0.5)])
    return shannon_entropy_from_counts(hist.ravel())


def finite_diff(x: np.ndarray, dt: float) -> np.ndarray:
    x = np.asarray(x, dtype=float)
    if x.size < 2:
        return np.zeros_like(x)
    return np.gradient(x, dt)


def mean_abs_angular_velocity(theta_dot: np.ndarray, phi_dot: np.ndarray) -> float:
    theta_dot = np.asarray(theta_dot, dtype=float)
    phi_dot = np.asarray(phi_dot, dtype=float)
    return float(np.mean((np.abs(theta_dot) + np.abs(phi_dot)) / 2.0))


def path_length(x: np.ndarray, y: np.ndarray) -> float:
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    if x.size < 2:
        return 0.0
    dx = np.diff(x)
    dy = np.diff(y)
    return float(np.sum(np.hypot(dx, dy)))


# ============================================================
# Data structures
# ============================================================

@dataclass
class RewardParams:
    # 9 weights
    w_stab: float
    w_freq: float
    w_move: float
    w_sway: float
    w_smooth: float
    w_torque: float
    w_vel: float
    w_ent: float
    w_target: float

    # 4 targets
    f_target: float
    v_target: float
    L_target: float
    S_target: float

    @classmethod
    def from_array(cls, arr: np.ndarray) -> "RewardParams":
        arr = np.asarray(arr, dtype=float).flatten()
        if arr.size != 13:
            raise ValueError(f"Expected 13 parameters, got {arr.size}")
        return cls(*arr.tolist())

    def to_array(self) -> np.ndarray:
        return np.array(list(asdict(self).values()), dtype=float)


@dataclass
class Trajectory:
    t: np.ndarray
    x: np.ndarray
    y: np.ndarray
    theta: np.ndarray
    phi: np.ndarray
    theta_dot: np.ndarray
    phi_dot: np.ndarray


@dataclass
class TrajectoryMetrics:
    mean_abs_velocity: float
    dominant_frequency: float
    spectral_centroid: float
    entropy: float
    path_length: float
    sway_area: float


# ============================================================
# Human data loading and metric extraction
# ============================================================

def load_trajectory_from_csv(path: Path, sample_rate: float = SAMPLE_RATE) -> Trajectory:
    df = pd.read_csv(path)

    def find_col(candidates: List[str]) -> Optional[str]:
        lower_map = {c.lower().strip(): c for c in df.columns}
        for cand in candidates:
            if cand.lower() in lower_map:
                return lower_map[cand.lower()]
        return None

    x_col = find_col(["x", "cop_x", "pos_x"])
    y_col = find_col(["y", "cop_y", "pos_y"])
    theta_col = find_col(["theta", "angle_x", "sagittal_angle"])
    phi_col = find_col(["phi", "angle_y", "frontal_angle"])
    time_col = find_col(["t", "time", "timestamp"])

    if x_col is None or y_col is None:
        raise ValueError(f"{path.name}: could not find x/y COP columns.")

    x = df[x_col].to_numpy(dtype=float)
    y = df[y_col].to_numpy(dtype=float)

    if time_col is not None:
        t = df[time_col].to_numpy(dtype=float)
        if t.size >= 2:
            dt = float(np.median(np.diff(t)))
        else:
            dt = 1.0 / sample_rate
    else:
        dt = 1.0 / sample_rate
        t = np.arange(len(x)) * dt

    L = 0.85
    if theta_col is not None:
        theta = df[theta_col].to_numpy(dtype=float)
    else:
        theta = np.arcsin(np.clip(x / L, -1.0, 1.0))

    if phi_col is not None:
        phi = df[phi_col].to_numpy(dtype=float)
    else:
        phi = np.arcsin(np.clip(y / L, -1.0, 1.0))

    theta_dot = finite_diff(theta, dt)
    phi_dot = finite_diff(phi, dt)
    return Trajectory(t=t, x=x, y=y, theta=theta, phi=phi, theta_dot=theta_dot, phi_dot=phi_dot)


def load_human_trajectories(data_dir: Path) -> List[Trajectory]:
    if not data_dir.exists():
        raise FileNotFoundError(f"Human data directory not found: {data_dir.resolve()}")

    files = sorted(list(data_dir.glob("*.csv")))
    if not files:
        raise FileNotFoundError(
            f"No CSV files found in {data_dir.resolve()}. "
            "Place the human COP trajectories there."
        )

    trajectories = []
    for fp in files:
        traj = load_trajectory_from_csv(fp)
        trajectories.append(traj)
    return trajectories


def trajectory_metrics(traj: Trajectory, sample_rate: float = SAMPLE_RATE) -> TrajectoryMetrics:
    mav = mean_abs_angular_velocity(traj.theta_dot, traj.phi_dot)
    dom_f, centroid = dominant_frequency_and_centroid(traj.theta, fs=sample_rate)
    ent = compute_entropy_2d(traj.theta, traj.phi, bins=16)
    plen = path_length(traj.x, traj.y)
    area = safe_convex_hull_area(traj.x, traj.y)
    return TrajectoryMetrics(
        mean_abs_velocity=mav,
        dominant_frequency=dom_f,
        spectral_centroid=centroid,
        entropy=ent,
        path_length=plen,
        sway_area=area,
    )


def metrics_from_arrays(
    theta: np.ndarray,
    phi: np.ndarray,
    x: np.ndarray,
    y: np.ndarray,
    dt: float = DT,
) -> TrajectoryMetrics:
    theta = np.asarray(theta, dtype=float)
    phi = np.asarray(phi, dtype=float)
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    theta_dot = finite_diff(theta, dt)
    phi_dot = finite_diff(phi, dt)
    traj = Trajectory(
        t=np.arange(len(x)) * dt,
        x=x,
        y=y,
        theta=theta,
        phi=phi,
        theta_dot=theta_dot,
        phi_dot=phi_dot,
    )
    return trajectory_metrics(traj)


def summarize_human_targets(metrics_list: List[TrajectoryMetrics]) -> Dict[str, float]:
    arr = {
        "mean_abs_velocity": np.array([m.mean_abs_velocity for m in metrics_list], dtype=float),
        "dominant_frequency": np.array([m.dominant_frequency for m in metrics_list], dtype=float),
        "spectral_centroid": np.array([m.spectral_centroid for m in metrics_list], dtype=float),
        "entropy": np.array([m.entropy for m in metrics_list], dtype=float),
        "path_length": np.array([m.path_length for m in metrics_list], dtype=float),
        "sway_area": np.array([m.sway_area for m in metrics_list], dtype=float),
    }
    return {k: float(np.mean(v)) for k, v in arr.items()}


# ============================================================
# Environment
# ============================================================

class RhythmicStandingEnv(gym.Env):
    metadata = {"render_modes": []}

    def __init__(self, reward_params: RewardParams):
        super().__init__()

        self.g = 9.81
        self.L = 0.85
        self.M = 71.83
        self.I = (self.M * self.L**2) / 3.0
        self.beta = 4.0
        self.tau_max = 75.0
        self.dt = DT
        self.max_steps = MAX_STEPS

        # Oscillator constants
        self.A_theta = 0.08
        self.A_phi = 0.08
        self.alpha = 0.45
        self.gamma_osc = 0.08

        # Reward parameters
        self.reward_params = reward_params

        # Action space: normalized torques in [-1, 1]
        self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(2,), dtype=np.float32)

        # Observation: 16 dims
        self.observation_space = spaces.Box(
            low=-np.inf, high=np.inf, shape=(16,), dtype=np.float32
        )

        self.state = None
        self.steps = 0
        self.prev_action = np.zeros(2, dtype=float)
        self.prev_x = 0.0
        self.prev_y = 0.0
        self.episode_x: List[float] = []
        self.episode_y: List[float] = []
        self.theta_window = deque(maxlen=64)
        self.phi_window = deque(maxlen=64)

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)

        self.steps = 0
        self.prev_action = np.zeros(2, dtype=float)

        theta = self.np_random.uniform(-0.01, 0.01)
        phi = self.np_random.uniform(-0.01, 0.01)
        dot_theta = self.np_random.uniform(-0.01, 0.01)
        dot_phi = self.np_random.uniform(-0.01, 0.01)
        psi = self.np_random.uniform(0, 2 * np.pi)
        x, y, v_x, v_y = 0.0, 0.0, 0.0, 0.0

        self.state = np.array([theta, phi, dot_theta, dot_phi, psi, x, y, v_x, v_y], dtype=float)
        self.prev_x = x
        self.prev_y = y
        self.episode_x = [x]
        self.episode_y = [y]
        self.theta_window.clear()
        self.phi_window.clear()
        self.theta_window.append(theta)
        self.phi_window.append(phi)

        return self._get_obs(), {}

    def step(self, action):
        action = np.asarray(action, dtype=float).flatten()
        action = np.clip(action, -1.0, 1.0)

        theta, phi, dot_theta, dot_phi, psi, x, y, v_x, v_y = self.state

        tau_theta = float(action[0] * self.tau_max)
        tau_phi = float(action[1] * self.tau_max)

        # Perturbations
        eps_theta = self.A_theta * np.sin(psi)
        eps_phi = self.A_phi * np.sin(psi + np.pi / 2.0)

        # Dynamics
        ddot_theta = (
            -(self.g / self.L) * np.sin(theta)
            + (tau_theta / self.I)
            - self.beta * dot_theta
            + eps_theta
        )
        ddot_phi = (
            -(self.g / self.L) * np.sin(phi)
            + (tau_phi / self.I)
            - self.beta * dot_phi
            + eps_phi
        )

        dot_psi = (
            2.0 * np.pi * self.reward_params.f_target
            + self.alpha * (abs(dot_theta) + abs(dot_phi))
            + self.gamma_osc * ((tau_theta - tau_phi) / self.tau_max)
        )

        # COP velocities
        v_x_new = 0.8 * v_x + 0.18 * abs(np.sin(psi)) + 0.05 * (abs(dot_theta) + abs(dot_phi))
        v_y_new = 0.7 * v_y + 0.03 * np.sin(psi + np.pi / 2.0) + 0.01 * (phi - theta)

        # Semi-implicit Euler
        theta = theta + dot_theta * self.dt
        phi = phi + dot_phi * self.dt
        dot_theta = dot_theta + ddot_theta * self.dt
        dot_phi = dot_phi + ddot_phi * self.dt
        psi = psi + dot_psi * self.dt
        x = x + v_x_new * self.dt
        y = y + v_y_new * self.dt

        self.state = np.array([theta, phi, dot_theta, dot_phi, psi, x, y, v_x_new, v_y_new], dtype=float)
        self.steps += 1

        self.episode_x.append(x)
        self.episode_y.append(y)
        self.theta_window.append(theta)
        self.phi_window.append(phi)

        fall_threshold = math.radians(FALL_THRESHOLD_DEG)
        terminated = bool(abs(theta) > fall_threshold or abs(phi) > fall_threshold)
        truncated = bool(self.steps >= self.max_steps)

        reward = self._calculate_reward(action, terminated, truncated, dot_psi, x, y, v_x_new, v_y_new)
        self.prev_action = action.copy()
        self.prev_x = x
        self.prev_y = y

        return self._get_obs(), float(reward), terminated, truncated, {}

    def _get_obs(self):
        theta, phi, dot_theta, dot_phi, psi, x, y, v_x, v_y = self.state
        time_frac = self.steps / self.max_steps

        return np.array(
            [
                theta, phi, dot_theta, dot_phi, psi, x, y, v_x, v_y,
                np.sin(theta), np.cos(theta),
                np.sin(phi), np.cos(phi),
                np.sin(psi), np.cos(psi),
                time_frac,
            ],
            dtype=np.float32,
        )

    def _reward_entropy(self) -> float:
        # Sliding-window entropy over posture angles
        theta_vals = np.array(self.theta_window, dtype=float)
        phi_vals = np.array(self.phi_window, dtype=float)
        if theta_vals.size < 6 or phi_vals.size < 6:
            return 0.0

        hist, _, _ = np.histogram2d(theta_vals, phi_vals, bins=8, range=[(-0.5, 0.5), (-0.5, 0.5)])
        return shannon_entropy_from_counts(hist.ravel())

    def _terminal_target_reward(self) -> float:
        # Match episode path length and sway area to targets
        x = np.array(self.episode_x, dtype=float)
        y = np.array(self.episode_y, dtype=float)
        plen = path_length(x, y)
        area = safe_convex_hull_area(x, y)

        L_t = self.reward_params.L_target
        S_t = self.reward_params.S_target

        r_L = np.exp(-((plen - L_t) / (abs(L_t) + 1e-6)) ** 2)
        r_S = np.exp(-((area - S_t) / (abs(S_t) + 1e-6)) ** 2)
        return self.reward_params.w_target * 0.5 * (r_L + r_S)

    def _calculate_reward(self, action, terminated, truncated, dot_psi, x, y, v_x, v_y):
        theta, phi, dot_theta, dot_phi, psi, _, _, _, _ = self.state

        p = self.reward_params

        # 1) Stability
        sigma = 0.1
        r_stab = p.w_stab * np.exp(-(theta**2 + phi**2) / (2.0 * sigma**2))

        # 2) Frequency matching
        current_f = dot_psi / (2.0 * np.pi)
        r_freq = p.w_freq * np.exp(-((current_f - p.f_target) / (abs(p.f_target) + 1e-6)) ** 2)

        # 3) Movement and sway
        delta_x = v_x * self.dt
        delta_y = v_y * self.dt
        r_move = -p.w_move * (abs(delta_x) + abs(delta_y))
        r_sway = p.w_sway * abs(delta_y)

        # 4) Smoothness
        action_diff = np.linalg.norm(action - self.prev_action)
        r_smooth = p.w_smooth * np.exp(-0.5 * action_diff**2)

        # 5) Torque and velocity penalties
        r_torque = -p.w_torque * (action[0] ** 2 + action[1] ** 2)
        r_vel = -p.w_vel * ((abs(dot_theta) + abs(dot_phi)) / 2.0)

        # 6) Entropy proxy
        r_ent = p.w_ent * self._reward_entropy()

        # 7) Velocity target matching
        v_mean = (abs(dot_theta) + abs(dot_phi)) / 2.0
        r_vtarget = 0.75 * np.exp(-((v_mean - p.v_target) / (abs(p.v_target) + 1e-6)) ** 2)

        # 8) Survival / fall logic
        r_survival = 1.0 if not terminated else -8.0

        # 9) Terminal summary-stat matching (path length + sway area)
        r_target = 0.0
        if terminated or truncated:
            r_target = self._terminal_target_reward()

        total_reward = (
            r_stab + r_freq + r_move + r_sway + r_smooth +
            r_torque + r_vel + r_ent + r_vtarget + r_survival + r_target
        )
        return float(total_reward)


# ============================================================
# PPO training / evaluation
# ============================================================

def build_ppo_model(env: gym.Env, seed: int = SEED) -> PPO:
    policy_kwargs = dict(
        activation_fn=nn.Tanh,
        net_arch=dict(pi=[256, 256], vf=[256, 256]),
    )

    model = PPO(
        "MlpPolicy",
        env,
        gamma=0.995,
        gae_lambda=0.97,
        clip_range=0.2,
        learning_rate=3e-4,
        ent_coef=0.008,
        n_epochs=8,
        batch_size=256,
        max_grad_norm=0.6,
        policy_kwargs=policy_kwargs,
        verbose=0,
        seed=seed,
        device="auto",
    )
    return model


def rollout_episode(model: PPO, env: gym.Env, deterministic: bool = True) -> Tuple[Trajectory, float, int]:
    obs, _ = env.reset()
    done = False
    total_reward = 0.0
    steps = 0

    xs, ys, thetas, phis = [], [], [], []

    while not done:
        action, _ = model.predict(obs, deterministic=deterministic)
        obs, reward, terminated, truncated, _ = env.step(action)

        total_reward += float(reward)
        steps += 1

        theta, phi, dot_theta, dot_phi, psi, x, y, v_x, v_y = env.state
        xs.append(x)
        ys.append(y)
        thetas.append(theta)
        phis.append(phi)

        done = bool(terminated or truncated)

    traj = Trajectory(
        t=np.arange(steps) * env.dt,
        x=np.array(xs, dtype=float),
        y=np.array(ys, dtype=float),
        theta=np.array(thetas, dtype=float),
        phi=np.array(phis, dtype=float),
        theta_dot=finite_diff(np.array(thetas, dtype=float), env.dt),
        phi_dot=finite_diff(np.array(phis, dtype=float), env.dt),
    )
    return traj, total_reward, steps


def train_evaluate_ppo(
    reward_params: RewardParams,
    total_timesteps: int = PPO_TOTAL_TIMESTEPS,
    eval_episodes: int = EVAL_EPISODES_FOR_SCORE,
    seed: int = SEED,
) -> Tuple[float, PPO, Dict[str, float]]:
    env = RhythmicStandingEnv(reward_params)
    model = build_ppo_model(env, seed=seed)
    model.learn(total_timesteps=total_timesteps)

    episode_rewards = []
    episode_steps = []

    for _ in range(eval_episodes):
        traj, total_reward, steps = rollout_episode(model, env, deterministic=True)
        episode_rewards.append(total_reward)
        episode_steps.append(steps)

    mean_reward = float(np.mean(episode_rewards))
    mean_steps = float(np.mean(episode_steps))

    # Fitness used by the surrogate search
    score = mean_reward + 0.1 * mean_steps

    eval_summary = {
        "mean_episode_reward": mean_reward,
        "mean_survival_steps": mean_steps,
        "fitness_score": float(score),
    }
    return float(score), model, eval_summary


# ============================================================
# Statistical evaluation
# ============================================================

def compare_distributions(human_vals: np.ndarray, agent_vals: np.ndarray) -> Dict[str, object]:
    human_vals = np.asarray(human_vals, dtype=float)
    agent_vals = np.asarray(agent_vals, dtype=float)

    human_p = np.nan
    agent_p = np.nan
    human_normal = False
    agent_normal = False

    if len(human_vals) >= 3 and len(human_vals) <= 5000:
        try:
            human_p = shapiro(human_vals).pvalue
            human_normal = bool(human_p > 0.05)
        except Exception:
            human_p = np.nan

    if len(agent_vals) >= 3 and len(agent_vals) <= 5000:
        try:
            agent_p = shapiro(agent_vals).pvalue
            agent_normal = bool(agent_p > 0.05)
        except Exception:
            agent_p = np.nan

    if human_normal and agent_normal:
        test_name = "Welch_t"
        stat, p = ttest_ind(human_vals, agent_vals, equal_var=False, nan_policy="omit")
    else:
        test_name = "Mann_Whitney_U"
        stat, p = mannwhitneyu(human_vals, agent_vals, alternative="two-sided")

    return {
        "human_mean": float(np.mean(human_vals)),
        "agent_mean": float(np.mean(agent_vals)),
        "human_shapiro_p": None if np.isnan(human_p) else float(human_p),
        "agent_shapiro_p": None if np.isnan(agent_p) else float(agent_p),
        "test": test_name,
        "statistic": float(stat),
        "p_value": float(p),
        "significant": bool(p < 0.05),
    }


def evaluate_agent_vs_human(
    human_metrics: List[TrajectoryMetrics],
    agent_trajectories: List[Trajectory],
) -> pd.DataFrame:
    human_dict = {
        "mean_abs_velocity": np.array([m.mean_abs_velocity for m in human_metrics], dtype=float),
        "dominant_frequency": np.array([m.dominant_frequency for m in human_metrics], dtype=float),
        "spectral_centroid": np.array([m.spectral_centroid for m in human_metrics], dtype=float),
        "entropy": np.array([m.entropy for m in human_metrics], dtype=float),
        "path_length": np.array([m.path_length for m in human_metrics], dtype=float),
        "sway_area": np.array([m.sway_area for m in human_metrics], dtype=float),
    }

    agent_metrics = [trajectory_metrics(tr) for tr in agent_trajectories]
    agent_dict = {
        "mean_abs_velocity": np.array([m.mean_abs_velocity for m in agent_metrics], dtype=float),
        "dominant_frequency": np.array([m.dominant_frequency for m in agent_metrics], dtype=float),
        "spectral_centroid": np.array([m.spectral_centroid for m in agent_metrics], dtype=float),
        "entropy": np.array([m.entropy for m in agent_metrics], dtype=float),
        "path_length": np.array([m.path_length for m in agent_metrics], dtype=float),
        "sway_area": np.array([m.sway_area for m in agent_metrics], dtype=float),
    }

    rows = []
    for key in human_dict:
        res = compare_distributions(human_dict[key], agent_dict[key])
        rows.append({
            "metric": key,
            "human_mean": res["human_mean"],
            "agent_mean": res["agent_mean"],
            "human_shapiro_p": res["human_shapiro_p"],
            "agent_shapiro_p": res["agent_shapiro_p"],
            "test": res["test"],
            "statistic": res["statistic"],
            "p_value": res["p_value"],
            "significant": res["significant"],
        })

    df = pd.DataFrame(rows)
    return df


# ============================================================
# Surrogate-assisted optimization
# ============================================================

PARAM_NAMES = [
    "w_stab", "w_freq", "w_move", "w_sway", "w_smooth", "w_torque",
    "w_vel", "w_ent", "w_target", "f_target", "v_target", "L_target", "S_target"
]

BOUNDS = np.array([
    [0.1, 10.0],    # w_stab
    [0.1, 10.0],    # w_freq
    [0.0, 5.0],     # w_move
    [0.0, 5.0],     # w_sway
    [0.1, 5.0],     # w_smooth
    [0.0, 2.0],     # w_torque
    [0.0, 2.0],     # w_vel
    [0.0, 2.0],     # w_ent
    [0.0, 5.0],     # w_target
    [0.001, 1.0],   # f_target
    [0.01, 0.2],    # v_target
    [10.0, 2000.0], # L_target
    [1e-4, 1e-1],   # S_target
], dtype=float)


def sample_candidate(rng: np.random.Generator, human_targets: Dict[str, float]) -> np.ndarray:
    cand = np.zeros(len(PARAM_NAMES), dtype=float)

    # Weights: broad uniform sampling
    for i in range(9):
        low, high = BOUNDS[i]
        cand[i] = rng.uniform(low, high)

    # Targets: centered near human statistics, clipped to bounds
    target_map = {
        9: human_targets["dominant_frequency"],
        10: human_targets["mean_abs_velocity"],
        11: human_targets["path_length"],
        12: human_targets["sway_area"],
    }
    for idx, center in target_map.items():
        low, high = BOUNDS[idx]
        scale = 0.35 if idx in (9, 10) else 0.50
        val = rng.normal(loc=center, scale=max(abs(center) * scale, 1e-6))
        cand[idx] = np.clip(val, low, high)

    return cand


def candidate_to_params(candidate: np.ndarray) -> RewardParams:
    return RewardParams.from_array(candidate)


def surrogate_optimization_pipeline(
    human_metrics: List[TrajectoryMetrics],
    total_timesteps: int = PPO_TOTAL_TIMESTEPS,
    final_timesteps: int = PPO_FINAL_TIMESTEPS,
    seed: int = SEED,
) -> Tuple[RewardParams, PPO, pd.DataFrame]:
    rng = np.random.default_rng(seed)
    human_targets = summarize_human_targets(human_metrics)

    X = []
    y = []
    scores = []

    print("Initializing surrogate-assisted optimization pipeline...")
    print("Human reference targets:")
    print(json.dumps(human_targets, indent=2))

    # Initial design
    print(f"\nStage 1: Initial design (n={INITIAL_DESIGN_N})")
    for i in range(INITIAL_DESIGN_N):
        cand = sample_candidate(rng, human_targets)
        params = candidate_to_params(cand)
        score, _, summary = train_evaluate_ppo(params, total_timesteps=total_timesteps, seed=seed + i)

        X.append(cand)
        y.append(score)
        scores.append(summary)

        print(f"  Initial config {i + 1}/{INITIAL_DESIGN_N} | score={score:.3f} | "
              f"reward={summary['mean_episode_reward']:.3f} | steps={summary['mean_survival_steps']:.1f}")

    X = np.array(X, dtype=float)
    y = np.array(y, dtype=float)

    surrogate = RandomForestRegressor(
        n_estimators=300,
        random_state=seed,
        n_jobs=-1,
    )

    # Guided iterations
    print(f"\nStage 2: Guided iterations ({GUIDED_ITERS} rounds)")
    for it in range(GUIDED_ITERS):
        surrogate.fit(X, y)

        candidates = np.array([sample_candidate(rng, human_targets) for _ in range(CANDIDATES_PER_ITER)])
        pred = surrogate.predict(candidates)
        best_idx = int(np.argmax(pred))
        best_candidate = candidates[best_idx]

        actual_score, _, summary = train_evaluate_ppo(
            candidate_to_params(best_candidate),
            total_timesteps=total_timesteps,
            seed=seed + 100 + it,
        )

        X = np.vstack([X, best_candidate])
        y = np.append(y, actual_score)
        scores.append(summary)

        print(f"  Iteration {it + 1}/{GUIDED_ITERS} | "
              f"pred={pred[best_idx]:.3f} | actual={actual_score:.3f} | "
              f"reward={summary['mean_episode_reward']:.3f} | steps={summary['mean_survival_steps']:.1f}")

    best_idx = int(np.argmax(y))
    best_candidate = X[best_idx]
    best_params = candidate_to_params(best_candidate)

    print("\nOptimization complete.")
    print(f"Best observed score: {y[best_idx]:.3f}")
    print("Best parameter vector:")
    print(dict(zip(PARAM_NAMES, best_candidate.tolist())))

    # Final longer training run
    print(f"\nStage 3: Final training run ({final_timesteps} timesteps)")
    final_env = RhythmicStandingEnv(best_params)
    final_model = build_ppo_model(final_env, seed=seed)
    final_model.learn(total_timesteps=final_timesteps)

    # Save artifacts
    joblib.dump(surrogate, OUTPUT_DIR / "rf_surrogate.joblib")
    final_model.save(str(OUTPUT_DIR / "final_ppo_model"))
    with open(OUTPUT_DIR / "best_reward_params.json", "w", encoding="utf-8") as f:
        json.dump(
            {name: float(val) for name, val in zip(PARAM_NAMES, best_candidate.tolist())},
            f,
            indent=2,
        )
    pd.DataFrame(scores).to_csv(OUTPUT_DIR / "training_summaries.csv", index=False)

    return best_params, final_model, pd.DataFrame(scores)


# ============================================================
# Main
# ============================================================

def main():
    set_global_seed(SEED)

    # Load human trajectories and compute reference metrics
    human_trajectories = load_human_trajectories(DATA_DIR)
    human_metrics = [trajectory_metrics(traj) for traj in human_trajectories]

    human_df = pd.DataFrame([asdict(m) for m in human_metrics])
    human_df.to_csv(OUTPUT_DIR / "human_metrics.csv", index=False)

    # Surrogate-assisted optimization
    best_params, final_model, optimization_log = surrogate_optimization_pipeline(
        human_metrics=human_metrics,
        total_timesteps=PPO_TOTAL_TIMESTEPS,
        final_timesteps=PPO_FINAL_TIMESTEPS,
        seed=SEED,
    )

    # Agent evaluation: 10 independent trajectories
    eval_env = RhythmicStandingEnv(best_params)
    agent_trajectories = []
    for i in range(EVAL_AGENT_TRAJ):
        traj, total_reward, steps = rollout_episode(final_model, eval_env, deterministic=True)
        agent_trajectories.append(traj)
        print(f"Agent rollout {i + 1}/{EVAL_AGENT_TRAJ}: reward={total_reward:.3f}, steps={steps}")

    # Statistical comparison against human trajectories
    comparison_df = evaluate_agent_vs_human(human_metrics, agent_trajectories)
    comparison_df.to_csv(OUTPUT_DIR / "human_vs_agent_statistics.csv", index=False)

    # Save a compact summary
    summary = {
        "best_params": {name: float(val) for name, val in zip(PARAM_NAMES, best_params.to_array().tolist())},
        "human_reference_means": summarize_human_targets(human_metrics),
        "stats_file": str((OUTPUT_DIR / "human_vs_agent_statistics.csv").resolve()),
        "model_file": str((OUTPUT_DIR / "final_ppo_model.zip").resolve()),
        "surrogate_file": str((OUTPUT_DIR / "rf_surrogate.joblib").resolve()),
    }
    with open(OUTPUT_DIR / "run_summary.json", "w", encoding="utf-8") as f:
        json.dump(summary, f, indent=2)

    print("\nFinal statistics:")
    print(comparison_df.to_string(index=False))
    print(f"\nAll outputs saved to: {OUTPUT_DIR.resolve()}")


if __name__ == "__main__":
    main()